export const englishTranslation = {
    coverPage: {
        introduction: 'Introduction',
        introductionSummary:
            'This report is designed to help you understand a candidate&rsquo;s overall suitability to a role and/or your organization. The data presented here is based on information submitted in the job application and the candidate&rsquo;s responses to Pulsifi&rsquo;s psychometric assessments. Pulsifi&rsquo;s proprietary methodology combines global best practices and scientific research for a multi-dimensional approach to understanding individuals in the workplace. We recommend using the information within this report alongside other sources of candidate information for a holistic approach to evaluating candidate suitability.',
        gainInsight: 'Gain insight into a candidate',
        gainInsightSummary:
            'You&rsquo;ll find comprehensive information on the candidate laid out in a dynamic manner, allowing you to quickly understand their strengths, areas of development and gain insight into what makes them tick. You&rsquo;ll discover a candidate&rsquo;s:',
        gainInsightFitScore:
            '<b>Fit Scores</b> - Scores derived from resume, submitted information and assessment results ',
        gainInsightHardSkills:
            'Hard skills - Competencies derived from work experiences',
        gainInsightSoftTraits:
            'Soft traits - Work styles, work interests, work values and cognitive abilities',
        gainInsightReadThisReport:
            'As you read this report, remember the following points:',
        gainInsightReadThisReportPoint1:
            'An individual&rsquo;s personality and ability can vary over time and improve through training and development',
        gainInsightReadThisReportPoint2:
            'A candidate&rsquo;s scores and insights are merely indicators of their preferences and behavioral tendencies and are not definitive judgements on the individual',
        gainInsightReadThisReportPoint3:
            'The report aims to clarify the individual&rsquo;s self-perception - it does not provide an objective measure',
        confidentiality: 'Confidentiality',
        confidentialitySummary:
            'This report is generated by Pulsifi and contains information that is private and confidential. Only relevant personnel within the organization can access this report.',
    },
    summaryPage: {
        breakDown: 'Breakdown',
        assessments: 'Assessments',
        appliedPosition: 'Applied Position',
        applicationStage: 'Applicant Stage',
        workExperienceNotAvailable: 'No career information yet.',
        workExperienceInformation:
            'Experience matched against those relevant to the role',
        completedAssessment: 'Completed',
        completedAssessmentOutOf: 'out of',
        screeningStatus: 'Screening Status',
        qualified: 'Qualified',
        unQualified: 'Unqualified',
        screeningTags: 'Screening Tags',
        screeningTagsMatched: 'Matched to requirements',
        screeningTagsRequired: 'Not a match',
        screeningTagsNotAvailable: 'No screening tags available.',
        roleFit: 'Role Fit',
        roleFitNotAvailable: 'N/A',
        roleFitSummary:
            'Job components are arranged in order of importance. Assess candidate suitability by comparing weighted role fit scores against component weightage',
        workStyles: 'Work Styles',
        workInterests: 'Work Interests',
        workValues: 'Work Values',
        competencies: 'Required Skills',
        workExperience: 'Work Experience',
        cognitiveAbilities: 'Cognitive Abilities',
        percentileBetterThan: 'Better than',
        percentileOfOtherCandidates: 'of other candidates',
        percentileOfGeneralCandidates: 'of general candidates',
        competenciesMatched: 'Matched skills',
        competenciesRequired: 'Not a match',
        competenciesNotAvailable: 'No competencies information yet.',
        competenciesInformation:
            'Skills matched against those required by the role',
        legendVeryImportant: 'Very important component for this role',
        legendImportant: 'Important component for this role',
        componentWeightageHeader: 'Component Weightage',
        weightedScoreHeader: 'Weighted Score',
        breakdownLegendHigh: 'High',
        breakdownLegendAverage: 'Average',
        breakdownLegendLow: 'Low',
    },
    screeningPage: {
        screeningQuestionsResponse: 'Screening Questions & Responses',
        screeningQuestionsResponseNotAvailable:
            'No job specific information yet.',
    },
    overviewPage: {
        overviewTitle: 'Key Highlights',
        overviewSummary:
            ' This section summarises who the candidate is in a work environment. The information highlighted here is particularly useful when interviewing the candidate to determine whether their traits align with the job or could impact their performance in the workplace.',
        traitsNotDetected: 'No notable traits detected.',
        issuesNotDetected: 'No notable issues detected.',
        whatMakes: 'What makes',
        whatMakesGreat: 'great',
        whatMakesThrive: 'thrive',
        whatToLookOutFor: 'What to look out for with',
    },
    cultureFitPage: {
        organizationFit: 'Organizational Fit',
        notAvailable: 'No organization fit information yet.',
    },
    workStylesPage: {
        workStyles: 'Work Styles',
        workStylesSummary:
            'Distinctive and stable character traits that define an individual and influences their general behavior in the workplace.',
        notAvailable: 'No work styles information yet.',
    },
    workInterestPage: {
        workInterests: 'Work Interests',
        workInterestsSummary:
            ' An individual&rsquo;s interest and preference toward different types of work.',
        notAvailable: 'No work interests information yet.',
    },
    workValuesPage: {
        workValues: 'Work Values',
        workValuesSummary:
            ' Aspects that are important to an individual&rsquo;s satisfaction and motivation in the workplace.',
        notAvailable: 'No work values information yet.',
    },
    cognitiveAbilitiesPage: {
        cognitiveAbilities: 'Cognitive Abilities',
        cognitiveAbilitiesReasoningLogical: 'Logical Reasoning',
        cognitiveAbilitiesReasoningVerbal: 'Verbal Reasoning',
        cognitiveAbilitiesReasoningNumeric: 'Numeric Reasoning',
        cognitiveAbilitiesSummary:
            'A measure of an individual&rsquo;s ability to learn, process information and solve problems.',
        percentileBetterThan: 'Better than',
        percentileOfOtherCandidates: 'of other candidates',
        notAvailable: 'No cognitive abilities information yet.',
    },
    experiencesPage: {
        experience: 'Experience',
        professionalSummary: 'Professional Summary',
        skills: 'Skills',
        addedByCandidateWhenApplyingToThisRole:
            'Added by candidate when applying to this role',
        expert: 'Expert',
        proficient: 'Proficient',
        competent: 'Competent',
        beginner: 'Beginner',
        novice: 'Novice',
        workExperience: 'Work Experience',
        education: 'Education',
        at: 'at',
        in: 'in',
        cgpa: 'CGPA',
        secondMajor: 'Second major',
        present: 'Present',
        professionalSummaryNotAvailable: 'No information yet.',
        workExperienceNotAvailable: 'No prior work experience.',
        educationNotAvailable: 'No formal education.',
    },
    footerPage: {
        allRightsReserved: 'All rights reserved.',
        reportGeneratedOn: 'Report generated on',
    },
    faqPage: {
        frequentlyAskedQuestions: 'Frequently Asked Questions',
        whatsTheBestWayToRead:
            'What&rsquo;s the best way to read the information in this report?',
        whatsTheBestWayToReadSummary:
            'If available, the report will begin with Role Fit - an understanding of the candidate&rsquo;s compatibility or fit to the applied position. Gain insight into how well the candidate meets important job requirements, whether they have the necessary skills to perform well in the role and how much of their past experience is relevant within this context.',
        whatsTheBestWayToReadSummaryParagraph2:
            'Then, if available, move on to the Organizational Fit section to evaluate the candidate&rsquo;s suitability to your organization.',
        whatsTheBestWayToReadSummaryParagraph3:
            'Study the remainder of the report for deeper insights and detailed information on the candidate&rsquo;s Work Styles, Work Interests, Work Values, Cognitive Abilities and their Skills & Experience.',
        howDoIInterpretFitScore: 'How do I interpret Fit Score?',
        howDoIInterpretFitScoreParagraph1:
            '<b>Role Fit</b> score helps you assess a candidate&rsquo;s suitability to a role. It is calculated from the candidate&rsquo;s scores  on each component of the role, which are derived from their resume and assessment results. The scores are weighted according to importance so you can easily see how well a candidate meets the most important requirements of the role.',
        howDoIInterpretFitScoreParagraph2:
            '<b>Organization Fit</b> score helps you evaluate a candidate&rsquo;s compatibility with your organization. It is calculated based on the individual&rsquo;s psychometric assessment results.',
        howDoIInterpretFitScoreParagraph3:
            'Both scores have a maximum of 100%; the higher the score, the better the candidate fit.',
        WhySomeInsightStatementNegative:
            'Why are some insight statements negative despite the candidate having a high fit score?',
        WhySomeInsightStatementNegativeParagraph:
            'Fit scores are derived by taking into consideration multiple soft traits as assessed by the psychometric assessments. Therefore, an individual with a high fit score might score high on most traits but still score low on some traits. The statements serve to bring your attention to these insights so you may better assess the candidate.',
        WhySomeInsightStatementNegativeParagraph2:
            'Note: Traits can be found under each section of this report. “Achievement/Effort”, for example, is a trait under “Work Styles” while “Relationships” is a trait under “Work Values”.',
        howDoIChooseBetween2Candidates:
            'How do I choose between 2 individuals who have almost similar scores?',
        howDoIChooseBetween2CandidatesParagraph:
            'The role-fit breakdown shows job components arranged in order of importance in the form of weighted scores. Compare each candidate&rsquo;s scores on the most important job components to evaluate which individual might be better suited to the role. Then, review each candidate&rsquo;s trait scores to see which individual possesses traits that are more aligned with the role, team and culture.',
        howDoeWeAssessHowAnIndividualPerform:
            'How do we assess how an individual will perform or behave in certain situations?',
        howDoeWeAssessHowAnIndividualPerformParagraph:
            'Gain insight into how an individual might perform or behave by asking them questions and evaluating their responses. Pulsifi&rsquo;s Interview Kit provides questions based on traits crucial to the role and team. Let the questions aid you in probing the candidate during the interview and assess whether the candidate possesses certain behaviours or would react appropriately based on their past experiences.',
        areCertainTraitBetter: 'Are certain traits better than others?',
        areCertainTraitBetterParagraph:
            'No, every trait contributes to the fit score and is relevant. However, the perceived importance of certain traits can vary depending on context and is largely dependent on the individual&rsquo;s role in the organization, the team&rsquo;s dynamics and the organization&rsquo;s culture.',
        besideHiringHowCanThisReportHelpMe:
            'Besides the hiring process, how can this report help me?',
        besideHiringHowCanThisReportHelpMeParagraph:
            'You can also use the insights detailed in this report&rsquo;s <b>Work Styles</b>, <b>Work Interests</b>, <b>Work Values</b> and <b>Cognitive Abilities</b> sections to identify a candidate&rsquo;s strengths and areas of development for successful onboarding, to craft a successful talent development plan and to strategize how you can maximize the individual&rsquo;s contribution to the team and organization.',
    },
    interviewCoverPage: {
        overallScore: 'Overall Score',
        ratings: 'Ratings',
        ratingBased: 'Based on the opinion of {{value}} people',
        allRatingAndReviews: 'All Ratings & Reviews',
    },
    interviewRatingText: {
        veryPoor: 'Very Poor',
        poor: 'Poor',
        average: 'Average',
        good: 'Good',
        excellent: 'Excellent',
    },
    interviewResponsePage: {
        interviewResponseBy: 'Interview Response By {{value}}',
        endOfReport: '--End of Report--',
    },
    applicationStatusText: {
        sourced: 'sourced',
        applied: 'applied',
        shortlisted: 'shortlisted',
        interviewed: 'interviewed',
        offered: 'offered',
        hired: 'hired',
        rejected: 'rejected',
        withdrawn: 'withdrawn',
    },
};

export const portugueseBrazilTranslation = {
    coverPage: {
        introduction: 'Introdução',
        introductionSummary:
            'Este relatório foi elaborado para ajudar a entender a adequação geral de um candidato a uma função e/ou à cultura da sua organização. Os resultados deste relatório foram gerados a partir das respostas do candidato às avaliações psicométricas da Pulsifi. A metodologia proprietária da Pulsifi combina as melhores práticas globais e pesquisas científicas em uma abordagem multidimensional para entender os indivíduos no local de trabalho. Recomendamos usar as informações contidas neste relatório em conjunto com outras fontes de informações do candidato, como as respostas em entrevistas.',
        gainInsight: 'Veja informações sobre um candidato',
        gainInsightSummary:
            'Você encontrará informações abrangentes sobre o candidato apresentadas de maneira dinâmica, que permitem entender rapidamente os pontos fortes, áreas de desenvolvimento dele e ter informações sobre o que o motiva. Você descobrirá sobre o candidato:',
        gainInsightHardSkills:
            'Hard skills - Competências derivadas de experiências de trabalho',
        gainInsightSoftTraits:
            'Soft traits - Estilos, interesses e valores de trabalho e habilidades cognitivas',
        gainInsightReadThisReport:
            'Ao ler este relatório, lembre-se dos seguintes pontos:',
        gainInsightReadThisReportPoint1:
            'A personalidade e a capacidade de um indivíduo podem variar com o tempo e melhorar com treinamento e desenvolvimento.',
        gainInsightReadThisReportPoint2:
            'Estes não são julgamentos definitivos sobre o indivíduo. As pontuações e demonstrações de insight são meramente indicadores das preferências ou tendências comportamentais dele.',
        gainInsightReadThisReportPoint3:
            'O perfil visa esclarecer a autopercepção do indivíduo, sendo que não fornece uma avaliação objetiva.',
        confidentiality: 'Confidencialidade',
        confidentialitySummary:
            'Este relatório é gerado pela Pulsifi e contém informações particulares e confidenciais. Somente o pessoal relevante dentro da organização pode acessar este relatório.',
    },
    summaryPage: {
        breakDown: 'Detalhamento',
        assessments: 'Avaliações',
        appliedPosition: 'Cargo candidatado',
        applicationStage: 'Fase de Candidatura',
        workExperienceNotAvailable:
            'Ainda não há informações sobre a carreira.',
        completedAssessment: 'Concluída',
        completedAssessmentOutOf: 'de',
        screeningStatus: 'Status de triagem',
        qualified: 'Qualificado',
        unQualified: 'Não qualificado',
        screeningTags: 'Tags de triagem',
        screeningTagsMatched: 'Atendidas',
        screeningTagsRequired: 'Obrigatórias',
        screeningTagsNotAvailable: 'Nenhuma tag de triagem disponível.',
        roleFit: 'Adequação à Função',
        roleFitNotAvailable: 'N/D',
        roleFitSummary:
            'A Adequação à Função é composta pelos seguintes componentes, organizados em ordem de importância.',
        workStyles: 'Estilos de trabalho',
        workInterests: 'Interesses de trabalho',
        workValues: 'Valores de trabalho',
        competencies: 'Competências',
        workExperience: 'Experiência de trabalho',
        cognitiveAbilities: 'Habilidades cognitivas',
        percentileBetterThan: 'Melhor que',
        percentileOfOtherCandidates: 'de outros candidatos',
        percentileOfGeneralCandidates: 'dos candidatos gerais',
        competenciesMatched: 'Atendidas',
        competenciesRequired: 'Obrigatórias',
        competenciesNotAvailable:
            'Ainda não há informações sobre competências.',
        legendVeryImportant: 'Componente muito importante para esta função',
        legendImportant: 'Componente importante para esta função',
    },
    screeningPage: {
        screeningQuestionsResponse: 'Perguntas e respostas de triagem',
        screeningQuestionsResponseNotAvailable:
            'Ainda não há informações específicas sobre o trabalho.',
    },
    overviewPage: {
        overviewTitle: 'Visão geral',
        overviewSummary:
            'Esta seção resume quem é o candidato em um ambiente de trabalho. As informações destacadas aqui são muito úteis ao entrevistar o candidato para determinar se as características dele se alinham com o trabalho ou podem afetar seu desempenho no local de trabalho.',
        traitsNotDetected: 'Nenhum traço notável detectado.',
        issuesNotDetected: 'Nenhum problema notável detectado.',
        whatMakes: 'O que torna',
        whatMakesGreat: 'ótimo',
        whatMakesThrive: 'prosperar',
        whatToLookOutFor: 'O que buscar em',
    },
    cultureFitPage: {
        organizationFit: 'Adequação da Organização',
        notAvailable: 'Nenhuma informação de adequação da organização ainda.',
    },
    workStylesPage: {
        workStyles: 'Estilos de trabalho',
        workStylesSummary:
            'Traços de caráter distintos e estáveis que definem um indivíduo e influenciam seu comportamento geral no local de trabalho.',
        notAvailable: 'Ainda não há informações sobre estilos de trabalho.',
    },
    workInterestPage: {
        workInterests: 'Interesses de trabalho',
        workInterestsSummary:
            'O interesse e a preferência de um indivíduo por diferentes tipos de trabalho.',
        notAvailable: 'Ainda não há informações de interesses de trabalho.',
    },
    workValuesPage: {
        workValues: 'Valores de trabalho',
        workValuesSummary:
            'Aspectos importantes para a satisfação e motivação de um indivíduo no ambiente de trabalho.',
        notAvailable: 'Ainda não há informações sobre valores de trabalho.',
    },
    cognitiveAbilitiesPage: {
        cognitiveAbilities: 'Habilidades cognitivas',
        cognitiveAbilitiesReasoningLogical: 'Raciocínio lógico',
        cognitiveAbilitiesReasoningVerbal: 'Raciocínio verbal',
        cognitiveAbilitiesReasoningNumeric: 'Raciocínio Numérico',
        cognitiveAbilitiesSummary:
            'Uma avaliação da capacidade de um indivíduo para aprender, processar informações e resolver problemas.',
        percentileBetterThan: 'Melhor que',
        percentileOfOtherCandidates: 'de outros candidatos',
        notAvailable: 'Ainda não há informações sobre habilidades cognitivas.',
    },
    footerPage: {
        allRightsReserved: 'Todos os direitos reservados.',
        reportGeneratedOn: 'Relatório gerado em',
    },
    faqPage: {
        frequentlyAskedQuestions: 'Perguntas Frequentes',
        whatsTheBestWayToRead:
            'Qual é a melhor forma de ler as informações neste relatório?',
        whatsTheBestWayToReadSummary:
            ' Se possível, comece com Adequação à Função para ter um panorama das competências do candidato e ver como ele se classifica perante componentes importantes do trabalho. Em seguida, veja a seção Visão geral para ter uma ideia da personalidade, comportamento e áreas de melhoria dele. Depois, se estiver disponível, examine a Adequação da Organização do candidato para avaliar a adequação à cultura da sua organização. Prossiga com o estudo do restante do relatório para ver percepções mais aprofundadas e informações detalhadas sobre os estilos, interesses e valores de trabalho e habilidades cognitivas do candidato.',
        howDoIInterpretFitScore: 'Como interpretar a Pontuação de Adequação?',
        howDoIInterpretFitScoreParagraph1:
            'A Pontuação de <b>Adequação à Função</b> ajuda a avaliar a aptidão de um candidato a uma função. Ela é derivada das hard skills e soft traits dos resultados da avaliação psicométrica do indivíduo e currículo.',
        howDoIInterpretFitScoreParagraph2:
            'A Pontuação de <b>Adequação da Organização</b> ajuda você a avaliar como um candidato se adaptaria à cultura da sua organização ou ao desempenho esperado. Ela é calculada com base nos resultados da avaliação psicométrica do indivíduo.',
        howDoIInterpretFitScoreParagraph3:
            'Tanto para a Pontuação de Adequação da Função quanto para a Pontuação de Adequação da organização, a Pontuação de Adequação varia de 0% a 100%; quanto maior a Pontuação de Adequação, melhor a aptidão do candidato.',
        WhySomeInsightStatementNegative:
            'Por que algumas demonstrações de insights são negativas, apesar de o candidato ter uma Pontuação de Adequação alta?',
        WhySomeInsightStatementNegativeParagraph:
            'A Pontuação de Adequação é derivada considerando vários soft traits, conforme aferidos pelas avaliações psicométricas. Portanto, um indivíduo com uma Pontuação de Adequação alta pode pontuar alto na maioria das características, mas pontuar baixo em algumas outras. As demonstrações servem para chamar sua atenção para esses insights, para que você possa avaliar melhor o candidato.',
        howDoIChooseBetween2Candidates:
            'Como faço para escolher entre dois indivíduos que têm pontuações de adequação quase iguais?',
        howDoIChooseBetween2CandidatesParagraph:
            'Consulte a seção Visão geral para se aprofundar nas pontuações de características do indivíduo. Foque nas características mais importantes para a função e a equipe. Escolha a pessoa que possui características mais alinhadas com a função, equipe e cultura.',
        howDoeWeAssessHowAnIndividualPerform:
            'Como avaliamos como um indivíduo se sairá ou se comportará em determinadas situações?',
        howDoeWeAssessHowAnIndividualPerformParagraph:
            'Você pode consultar o conjunto de perguntas listadas no Kit de Entrevista, que considera as características essenciais para a função ou equipe. Ele podem ajudar a sondar o candidato durante a entrevista e isso permitirá que você avalie de forma mais objetiva se o indivíduo apresenta certos comportamentos ou se reagiria adequadamente com base em suas experiências anteriores.',
        areCertainTraitBetter:
            'Algumas características são melhores do que outras?',
        areCertainTraitBetterParagraph:
            'Não, todas as características contribuem para a Pontuação de Adequação e são relevantes. Ainda assim, a importância percebida de certas características pode variar a cada contexto e depende muito do papel do indivíduo na organização, da dinâmica da equipe e da cultura da organização.',
        besideHiringHowCanThisReportHelpMe:
            'Além do processo de contratação, como esse relatório pode me ajudar?',
        besideHiringHowCanThisReportHelpMeParagraph:
            'Você também pode usar as informações detalhadas na seções <b>Estilos de trabalho</b>, <b>Interesses de trabalho</b>, <b>Valores de trabalho</b> e <b>Habilidades cognitivas</b> deste relatório para identificar os pontos fortes e áreas de desenvolvimento de um candidato para uma integração bem-sucedida, para elaborar um plano de desenvolvimento de talentos eficiente e criar estratégias para maximizar a contribuição do indivíduo junto à equipe e organização.',
    },
    interviewCoverPage: {
        overallScore: 'Pontuação geral',
        ratings: 'Avaliações',
        ratingBased: 'Com base na opinião de {{value}} pessoas',
        allRatingAndReviews: 'Todas as avaliações e comentários',
    },
    interviewRatingText: {
        veryPoor: 'Muito pobre',
        poor: 'Pobre',
        average: 'Média',
        good: 'Bom',
        excellent: 'Excelente',
    },
    interviewResponsePage: {
        interviewResponseBy: 'Resposta da entrevista por {{value}}',
        endOfReport: '--Fim do relatório--',
    },
    applicationStatusText: {
        sourced: 'originário',
        applied: 'aplicado',
        shortlisted: 'pré-selecionado',
        interviewed: 'entrevistado',
        offered: 'oferecido',
        hired: 'contratado',
        rejected: 'rejeitado',
        withdrawn: 'retirado',
    },
};

export const testData = {
    englishTranslation,
    portugueseBrazilTranslation,
};
