export enum CacheObject {
    PERSONALITY_FRAMEWORK_DETAIL = 'PERSONALITY:FRAMEWORK_DETAIL',
    PSYCHOLOGY_LANGUAGE = 'LANGUAGE',
    TALENT_ANALYTICS_JOB_RECIPE = 'TALENT_ANALYTICS:JOB_RECIPE',
    COMPANY_ID = 'COMPANY:COMPANY_ID',
    FIT_SCORE_RECIPE_ID = 'FIT_SCORE_RECIPE:RECIPE_ID',
}

export enum CacheTtl {
    ONE_MINUTE = 60 * 1000,
}
